import { useState } from 'react';
import { faqContent } from '../data/aiContent';

const FALLBACK_ITEMS = [
  {
    question: "If my income stopped today, how long could my family manage?",
    answer: 'Design sample answer — the real answer is generated by the AI pipeline from your profile once it has run.',
  },
];

// Chrome-free curated FAQ list (originally the phone-only /ask screen) —
// pre-generated by the AI pipeline against the demo profile, not live chat.
export default function FaqList() {
  const items = faqContent?.items?.length ? faqContent.items : FALLBACK_ITEMS;
  const [openIdx, setOpenIdx] = useState(0);

  return (
    <div style={{ background: '#fff', fontFamily: 'Archivo, sans-serif', color: '#201e1d' }}>
      <div style={{ padding: '14px 20px', borderBottom: '2px solid #201e1d', font: '400 12px/1.5 Archivo, sans-serif', color: '#5f5c5a' }}>
        Answers below are pre-generated by a scheduled AI pipeline against the demo profile
        (Rohan Prasad) — not a live, freeform chat. Pick a question to see its answer.
      </div>
      {items.map((item, i) => (
        <div key={i} style={{ borderBottom: i === items.length - 1 ? '2px solid #201e1d' : '1px solid #eceaea' }}>
          <div
            onClick={() => setOpenIdx(openIdx === i ? -1 : i)}
            style={{ padding: '14px 20px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', gap: 12 }}
          >
            <span style={{ font: '600 13px Archivo, sans-serif' }}>{item.question}</span>
            <span style={{ font: '600 13px Archivo, sans-serif', color: '#8a8785', flex: 'none' }}>
              {openIdx === i ? '−' : '+'}
            </span>
          </div>
          {openIdx === i && (
            <div style={{ padding: '0 20px 16px', font: '400 12px/1.6 Archivo, sans-serif', color: '#5f5c5a' }}>
              {item.answer}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
