import { useState } from 'react';
import { Link } from 'react-router-dom';
import { faqContent } from '../data/aiContent';
import { IOSDevice } from '../components/frames/IOSFrame';
import useDocumentTitle from '../hooks/useDocumentTitle';

const FALLBACK_ITEMS = [
  {
    question: "If my income stopped today, how long could my family manage?",
    answer: 'Design sample answer — the real answer is generated by the AI pipeline from your profile once it has run.',
  },
];

export default function Ask() {
  useDocumentTitle('Ask about your money');
  const items = faqContent?.items?.length ? faqContent.items : FALLBACK_ITEMS;
  const isAI = Boolean(faqContent?.items?.length);
  const [openIdx, setOpenIdx] = useState(0);

  return (
    <div>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 16,
          padding: '16px 24px',
          borderBottom: '2px solid var(--color-divider)',
        }}
      >
        <Link to="/app/home" style={{ color: 'var(--color-accent)', font: '600 11px Archivo, sans-serif' }}>
          ← APP
        </Link>
        <div>
          <div style={{ font: '600 10px ui-monospace, monospace', color: 'rgba(0,0,0,.5)' }}>
            {isAI ? 'AI-GENERATED · REFRESHED WEEKLY' : 'AWAITING FIRST PIPELINE RUN'}
          </div>
          <div style={{ font: '600 14px Archivo, sans-serif', marginTop: 2 }}>Ask about your money</div>
        </div>
      </div>

      <div style={{ display: 'flex', gap: 24, padding: '32px 24px', alignItems: 'flex-start' }}>
        <IOSDevice title="Ask">
          <div style={{ background: '#fff', fontFamily: 'Archivo, sans-serif', color: '#201e1d' }}>
            <div style={{ padding: '14px 20px', borderBottom: '2px solid #201e1d', font: '400 12px/1.5 Archivo, sans-serif', color: '#5f5c5a' }}>
              Answers below are pre-generated by a scheduled AI pipeline against the demo profile
              (Rohan Prasad) — not a live, freeform chat. Pick a question to see its answer.
            </div>
            {items.map((item, i) => (
              <div key={i} style={{ borderBottom: i === items.length - 1 ? '2px solid #201e1d' : '1px solid #eceaea' }}>
                <div
                  onClick={() => setOpenIdx(openIdx === i ? -1 : i)}
                  style={{ padding: '14px 20px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', gap: 12 }}
                >
                  <span style={{ font: '600 13px Archivo, sans-serif' }}>{item.question}</span>
                  <span style={{ font: '600 13px Archivo, sans-serif', color: '#8a8785', flex: 'none' }}>
                    {openIdx === i ? '−' : '+'}
                  </span>
                </div>
                {openIdx === i && (
                  <div style={{ padding: '0 20px 16px', font: '400 12px/1.6 Archivo, sans-serif', color: '#5f5c5a' }}>
                    {item.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </IOSDevice>

        <div style={{ maxWidth: 420, font: '400 12px/1.6 Archivo, sans-serif', color: 'rgba(0,0,0,.6)' }}>
          <p style={{ marginTop: 0 }}>
            This screen wasn't part of the original wireframe set — it's the "free-form chat
            assistant" AI feature, implemented as a curated, pre-generated FAQ rather than live
            chat, because a real GitHub Models token can't safely be called from browser
            JavaScript. A GitHub Action (<code>.github/workflows/ai-pipeline.yml</code>) runs the
            model weekly (or on demand) against <code>ai/profile.json</code> and commits the
            answers to <code>app/src/data/ai/faq.json</code>, which this screen reads.
          </p>
          {faqContent?.generated_at && (
            <p style={{ font: '500 10px/1.6 ui-monospace, monospace', color: '#8a8785' }}>
              GENERATED {new Date(faqContent.generated_at).toISOString()} · MODEL {faqContent.model}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
