import DvCard from '../components/DvCard';
import FaqList from '../components/FaqList';
import PageHeader from './PageHeader';
import { faqContent } from '../data/aiContent';
import useDocumentTitle from '../hooks/useDocumentTitle';

export default function WebsiteAsk() {
  useDocumentTitle('Ask about your money');
  const isAI = Boolean(faqContent?.items?.length);
  return (
    <div>
      <PageHeader
        kicker={isAI ? 'AI-GENERATED · REFRESHED WEEKLY' : 'AWAITING FIRST PIPELINE RUN'}
        title="Ask about your money"
        description="Pre-generated by a scheduled AI pipeline against the demo profile — not live, freeform chat. A GitHub Action refreshes these weekly via GitHub Models."
      />
      <DvCard width={520}>
        <FaqList />
      </DvCard>
    </div>
  );
}
